config/routes.rb
ArtSocnet::Application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }
  devise_scope :user do
    get 'signup',                          to: 'registrations#new'
  end

  resources :users  do
    resources :albums, shallow: true do
      resources :images
    end

    resources :messages, only: [:index, :show, :new, :create]
    resources :conversations, only: [:index, :show]
  end

  resources :conversations, only: [:show]
  resources :showman_types,     only: [:edit, :update]
  resources :restaurants,       only: [:edit, :update]
  resources :restaurant_types,  only: [:edit, :update]
  resources :cuisines,          only: [:edit, :update]

  root "static_pages#home"
  get '/help',                            to: 'static_pages#help'
  get '/contacts',                        to: 'static_pages#contacts'
  get '/allusers',                        to: 'static_pages#allusers' #change to index method?
  get '/allrestaurants',                  to: 'static_pages#allrestaurants'   

    get '/after_signup/step_2',                          to: 'after_signup#step_2'
    get '/after_signup/step_guest',                      to: 'after_signup#step_guest'
    get '/after_signup/step_showman',                    to: 'after_signup#step_showman'
    get '/after_signup/step_restaurant',                 to: 'after_signup#step_restaurant'
    get '/after_signup/step_restaurant_types',           to: 'after_signup#step_restaurant_types'
    get '/after_signup/step_cuisines',                   to: 'after_signup#step_cuisines'
    get '/after_signup/final_step',                      to: 'after_signup#final_step'
    patch '/after_signup/step_2_update',                 to: 'after_signup#step_2_update'
    patch '/after_signup/step_guest_update',             to: 'after_signup#step_guest_update'
    match '/after_signup/step_showman_update',           to: 'after_signup#step_showman_update',          via:[:patch, :post]
    match '/after_signup/step_restaurant_update',        to: 'after_signup#step_restaurant_update',       via:[:patch, :post]
    match '/after_signup/step_restaurant_types_update',  to: 'after_signup#step_restaurant_types_update', via:[:patch, :post]
    match '/after_signup/step_cuisines_update',          to: 'after_signup#step_cuisines_update',         via:[:patch, :post]
    match '/after_signup/final_step_update',             to: 'after_signup#final_step_update',         via:[:patch, :post]

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contacts

  end

  def allusers
    @users = User.where(usr_type: 'showman')
  end

  def allrestaurants
    @restaurants = User.where(usr_type: 'restaurant')
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/allrestaurants.html.erb
<h1>Рестораны</h1>
<div class="container">
  <div class="row">
    <div class="col-md-offset-2">
      <% @restaurants.each do |r| %>
          <div class="row">
            <div class="col-md-2">
              <%= link_to image_tag(r.avatar(:thumb), class: 'thumbnail'), r %>
            </div>
            <div class="col-md-4">
              <blockquote>
                <p><%= link_to r.restaurant.name, r %></p>
                <small><cite>
                  <% r.restaurant.restaurant_type.to_types_array(r.restaurant.restaurant_type).each do |t| %>
                      <%= (t + ' ') %>
                  <% end %>
                </cite><i class="glyphicon glyphicon-circle-arrow-left"></i></small>
              </blockquote>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/static_pages/allusers.html.erb
<h1>Люди</h1>
<div class="container">
  <div class="row">
    <div class="col-md-offset-2">
      <% @users.each do |u| %>
          <div class="row">
            <div class="col-md-2">
              <%= link_to image_tag(u.avatar(:thumb), class: 'thumbnail'), u %>
            </div>
            <div class="col-md-4">
              <blockquote>
                <p><%= link_to(u.firstname + ' ' + u.lastname, u) %></p>
                <small><cite>
                  <% u.showman_type.to_types_array(u.showman_type).each do |t| %>
                      <%= (t + ' ') %>
                  <% end %>
                </cite></small>
              </blockquote>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/static_pages/contacts.html.erb
<h1>Contacts</h1>
bla bla bla

app/views/static_pages/help.html.erb
<%= provide(:title, 'Помощь') %>
<h1>Помощь</h1>

app/views/static_pages/home.html.erb
<%= provide(:title, 'Главная') %>
<% if user_signed_in? %>
    <%= current_user.firstname %> signed in

<% else %>
    <h1>Главная</h1>

    <%= link_to "Зарегистрируйтесь!", signup_path,
                class: "btn btn-large btn-primary" %>
<% end %>
<ul>
  <li><%= link_to 'Люди', allusers_path %></li>
  <li><%= link_to 'Рестораны', allrestaurants_path %></li>
</ul>
     