config/routes.rb
ArtSocnet::Application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }
  devise_scope :user do
    get 'signup',                          to: 'registrations#new'
  end

  resources :users  do
    resources :albums, shallow: true do
      resources :images
    end

    resources :messages, only: [:index, :show, :new, :create]
    resources :conversations, only: [:index, :show]
  end

  resources :conversations, only: [:show]
  resources :showman_types,     only: [:edit, :update]
  resources :restaurants,       only: [:edit, :update]
  resources :restaurant_types,  only: [:edit, :update]
  resources :cuisines,          only: [:edit, :update]

  root "static_pages#home"
  get '/help',                            to: 'static_pages#help'
  get '/contacts',                        to: 'static_pages#contacts'
  get '/allusers',                        to: 'static_pages#allusers' #change to index method?
  get '/allrestaurants',                  to: 'static_pages#allrestaurants'   

    get '/after_signup/step_2',                          to: 'after_signup#step_2'
    get '/after_signup/step_guest',                      to: 'after_signup#step_guest'
    get '/after_signup/step_showman',                    to: 'after_signup#step_showman'
    get '/after_signup/step_restaurant',                 to: 'after_signup#step_restaurant'
    get '/after_signup/step_restaurant_types',           to: 'after_signup#step_restaurant_types'
    get '/after_signup/step_cuisines',                   to: 'after_signup#step_cuisines'
    get '/after_signup/final_step',                      to: 'after_signup#final_step'
    patch '/after_signup/step_2_update',                 to: 'after_signup#step_2_update'
    patch '/after_signup/step_guest_update',             to: 'after_signup#step_guest_update'
    match '/after_signup/step_showman_update',           to: 'after_signup#step_showman_update',          via:[:patch, :post]
    match '/after_signup/step_restaurant_update',        to: 'after_signup#step_restaurant_update',       via:[:patch, :post]
    match '/after_signup/step_restaurant_types_update',  to: 'after_signup#step_restaurant_types_update', via:[:patch, :post]
    match '/after_signup/step_cuisines_update',          to: 'after_signup#step_cuisines_update',         via:[:patch, :post]
    match '/after_signup/final_step_update',             to: 'after_signup#final_step_update',         via:[:patch, :post]

  

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :user
  has_many :images, dependent: :destroy

  validates :user_id, presence: true
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  has_many :messages, dependent: :destroy
  belongs_to :user1, class_name: 'User'
  belongs_to :user2, class_name: 'User'

  validates_presence_of :user1_id, :user2_id

  # get conversation between two users
  def self.get_conversation(user1, user2)
    @conversation = Conversation.where("(user1_id = ? AND user2_id = ?) OR (user1_id = ? AND user2_id = ?)",
                                       user1, user2,
                                       user2, user1).first

    if @conversation.nil?
      @conversation = Conversation.new do |c|
        c.user1_id = user1
        c.user2_id = user2
        #TODO: catch ex if can't save to db
        c.save
      end
    end
    @conversation
  end

  def self.all_conversations_for(user)
    Conversation.where("user1_id = ? OR user2_id = ?", user, user).order("updated_at DESC")
  end

  # return user object. Maybe return just id?
  # something stupidly wrong
  def get_other_recipient(current_user)
    # if self.user1 == current_user ? self.user1 : self.user2; end
    if self.user1 == current_user
      self.user2
    else
      self.user1
    end
  end

end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base
  include ModulesHelper
  belongs_to :restaurant

  validates :restaurant_id, presence: true, uniqueness: true
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :album
  has_attached_file :image, styles: {large: '600x600>', thumb: ['100x100>', :png]}

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
                                    #:content_type => %w(image/jpeg image/jpg image/png)
  validates :album_id, presence: true
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'

  validates_presence_of :content, :conversation_id
  validates_presence_of :sender_id, :recipient_id
  validates_length_of :content, maximum: 250
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  belongs_to :user
  has_one :cuisine, dependent: :destroy
  has_one :restaurant_type, dependent: :destroy

  #validates :name, presence: true, uniqueness: true
  #validates :city, presence: true
  #validates :password, length: {minimum: 6}
  #validates :password_confirmation, presence: true

end

app/models/restaurant_type.rb
class RestaurantType < ActiveRecord::Base
  include ModulesHelper

  belongs_to :restaurant

  validates :restaurant_id, presence: true, uniqueness: true
end

app/models/restaurant_types.rb
class RestaurantTypes < ActiveRecord::Base
  belongs_to :restaurant

  validates :restaurant_id, presence: true, uniqueness: true
end

app/models/showman_type.rb
class ShowmanType < ActiveRecord::Base
  include ModulesHelper
  belongs_to :user

  validates :user_id, presence: true, uniqueness: true

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save :ensure_authentication_token
  # Include default devise modules. Others available are:
  # :confirmable,
  # :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #, :token_authenticatable was deprecated. @see generate and ensure_authentication token

  has_attached_file :avatar, styles: {small: '300x300>', large: '600x600>',
                                      thumb: ['100x100>', :png]}, default_url: 'std_avatar.jpg'
  has_one :restaurant, dependent: :destroy
  has_one :showman_type, dependent: :destroy
  has_many :albums, dependent: :destroy
  # has_many :conversations, foreign_key: 'sender_id', dependent: :destroy
  # has_many :conversations, foreign_key: 'recipient_id', dependent: :destroy
  # has_many :recipients, through: :conversations, source: :recipient
  # has_many :recipients, through: :messages, source: :receiver

  #serialize :languages, Array
  #has_secure_password
  validates :email, presence: true, uniqueness: true
  #validates :password, presence: true
  #validates :password_confirmation, presence: true
  #validates :password_digest, presence: true
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def ensure_authentication_token
    if authentication_token.blank?
      self.authentication_token = generate_authentication_token
    end
  end

  private
  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless User.where(authentication_token: token).first
    end
  end
end

app/models/user_type.rb
class UserType < ActiveRecord::Base
  belongs_to :user

  validates :user_id, presence: true, uniqueness: true
end

app/helpers/after_signup_helper.rb
module AfterSignupHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/modules_helper.rb
module ModulesHelper
  def to_types_array(obj)
    a = Array.new
    obj.attributes.each do |key, value|
      a << key if value == true
    end
    a
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/refills/_footer.html.erb
<footer class="footer">
  <div class="footer-logo">
    <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_1.png" alt="">
  </div>
  <div class="footer-links">
    <ul>
      <li><h3>Content</h3></li>
      <li><a href="javascript:void(0)">About</a></li>
      <li><a href="javascript:void(0)">Contact</a></li>
      <li><a href="javascript:void(0)">Products</a></li>
    </ul>
    <ul>
      <li><h3>Follow Us</h3></li>
      <li><a href="javascript:void(0)">Facebook</a></li>
      <li><a href="javascript:void(0)">Twitter</a></li>
      <li><a href="javascript:void(0)">YouTube</a></li>
    </ul>
    <ul>
      <li><h3>Legal</h3></li>
      <li><a href="javascript:void(0)">Terms and Conditions</a></li>
      <li><a href="javascript:void(0)">Privacy Policy</a></li>
    </ul>
  </div>

  <hr>

  <p>Disclaimer area lorem ipsum dolor sit amet, consectetur adipisicing elit. Rerum, nostrum repudiandae saepe.</p>
</footer>

app/views/refills/_navigation.html.erb
<header class="navigation">
  <div class="menu-wrapper">
    <a href="javascript:void(0)" class="logo">
      <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_1.png" alt="">
    </a>
    <p class="navigation-menu-button" id="js-mobile-menu">MENU</p>
    <div class="nav">
      <ul id="navigation-menu">
        <li class="nav-link"><%= link_to 'Главная', root_path %></li>
        <li class="nav-link"><a href="javascript:void(0)">Сообщества</a></li>
        <li class="nav-link"><%= link_to 'Помощь', help_path %></li>
        <li class="nav-link"><a href="javascript:void(0)">Сервис</a></li>
        <!--<li class="nav-link more"><a href="javascript:void(0)">Че то еще</a>-->
          <!--<ul class="submenu">-->
            <!--<li><a href="javascript:void(0)">Submenu Item</a></li>-->
            <!--<li><a href="javascript:void(0)">Another Item</a></li>-->
          <!--</ul>-->
        <!--</li>-->
      </ul>
    </div>
    <div class="navigation-tools">
      <div class="search-bar">
        <div class="search-and-submit">
          <input type="search" placeholder="поиск" />
          <button type="submit">
            <img src="https://raw.githubusercontent.com/Magnus-G/Random/master/search-icon.png" alt="">
          </button>
        </div>
      </div>
      <% if user_signed_in? %>
          <ul id="navigation-menu">
          <li class="nav-link more"><a href="javascript:void(0)">Здравствуйте, <%= current_user.firstname %></a>
            <ul class="submenu">
              <li>
                <%= link_to user_path(current_user) do %>
                    <%= image_tag 'glyphicons_free/glyphicons/png/glyphicons_020_home.png' %> <mnu-txt>Моя страница</mnu-txt>
                <% end %>
              </li>
              <li>
                <%= link_to edit_user_path(current_user) do %>
                  <%= image_tag 'glyphicons_free/glyphicons/png/glyphicons_439_wrench.png' %> <mnu-txt>Настройки</mnu-txt>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <%= image_tag 'glyphicons_free/glyphicons/png/glyphicons_063_power.png' %> Выйти
                <% end %>
              </li>
            </ul>
          </li>
          </ul>
      <% else %>
          <%= link_to 'Регистрация', signup_path, class: 'reg-btn' %>
          <%= link_to 'Войдите', new_user_session_path, class: 'sign-up' %>
      <% end %>
    </div>
  </div>
</header>

app/views/shared/_contacts.html.erb
<%= f.label 'Страна' %>
<%= f.text_field :country %>

<%= f.label 'Город' %>
<%= f.text_field :city %>

<%= f.label 'Телефон' %>
<%= f.phone :phone %>

<%= f.label 'Skype' %>
<%= f.text_field :skype %>

<%= f.label 'Одноклассники' %>
<%= f.text_field :odkl %>

<%= f.label 'Вконтакте' %>
<%= f.text_field :vkontakte %>

<%= f.label 'Twitter' %>
<%= f.text_field :twitter %>

app/views/shared/_edit_tabs.html.erb
<ul class="nav nav-tabs" id="editTabs">
  <li> <%= link_to 'Основные', edit_user_path(user_id) %></li>
  <li><%= link_to 'Смена пароля', edit_user_registration_path(user_id) %></li>

  <li><%= link_to 'Альбомы', user_albums_path(user_id) %></li>
  <% if @user.usr_type == 'showman' %>
      <li><%= link_to 'Cпециализации', edit_showman_type_path(user_id) %></li>
  <% end %>
  <% if @user.usr_type == 'restaurant' %>
      <li><%= link_to 'Ресторан', edit_restaurant_path(user_id) %></li>
      <li><%= link_to 'Услуги ресторана', edit_restaurant_type_path(user_id) %></li>
      <li><%= link_to 'Кухня', edit_cuisine_path(user_id) %></li>
  <% end %>
</ul>

<script>
    /*menu handler*/
    $(function () {
        function stripTrailingSlash(str) {
            if (str.substr(-1) == '/') {
                return str.substr(0, str.length - 1);
            }
            return str;
        }

        var url = window.location.pathname;
        var activePage = stripTrailingSlash(url);

        $('.nav li a').each(function () {
            var currentPage = stripTrailingSlash($(this).attr('href'));

            if (activePage == currentPage) {
                $(this).parent().addClass('active');
            }
        });
    });
</script>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(object.errors.count, "error") %>
      </div>
      <ul>
        <%
           object.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>

        <% end %>
      </ul>
    </div>

<% end %>

app/views/shared/_first_last_name.html.erb
<%= f.label 'Имя' %>
<%= f.text_field :firstname %>

<%= f.label 'Фамилия' %>
<%= f.text_field :lastname %>