config/routes.rb
ArtSocnet::Application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }
  devise_scope :user do
    get 'signup',                          to: 'registrations#new'
  end

  resources :users  do
    resources :albums, shallow: true do
      resources :images
    end

    resources :messages, only: [:index, :show, :new, :create]
    resources :conversations, only: [:index, :show]
  end

  resources :conversations, only: [:show]
  resources :showman_types,     only: [:edit, :update]
  resources :restaurants,       only: [:edit, :update]
  resources :restaurant_types,  only: [:edit, :update]
  resources :cuisines,          only: [:edit, :update]

  root "static_pages#home"
  get '/help',                            to: 'static_pages#help'
  get '/contacts',                        to: 'static_pages#contacts'
  get '/allusers',                        to: 'static_pages#allusers' #change to index method?
  get '/allrestaurants',                  to: 'static_pages#allrestaurants'   

    get '/after_signup/step_2',                          to: 'after_signup#step_2'
    get '/after_signup/step_guest',                      to: 'after_signup#step_guest'
    get '/after_signup/step_showman',                    to: 'after_signup#step_showman'
    get '/after_signup/step_restaurant',                 to: 'after_signup#step_restaurant'
    get '/after_signup/step_restaurant_types',           to: 'after_signup#step_restaurant_types'
    get '/after_signup/step_cuisines',                   to: 'after_signup#step_cuisines'
    get '/after_signup/final_step',                      to: 'after_signup#final_step'
    patch '/after_signup/step_2_update',                 to: 'after_signup#step_2_update'
    patch '/after_signup/step_guest_update',             to: 'after_signup#step_guest_update'
    match '/after_signup/step_showman_update',           to: 'after_signup#step_showman_update',          via:[:patch, :post]
    match '/after_signup/step_restaurant_update',        to: 'after_signup#step_restaurant_update',       via:[:patch, :post]
    match '/after_signup/step_restaurant_types_update',  to: 'after_signup#step_restaurant_types_update', via:[:patch, :post]
    match '/after_signup/step_cuisines_update',          to: 'after_signup#step_cuisines_update',         via:[:patch, :post]
    match '/after_signup/final_step_update',             to: 'after_signup#final_step_update',         via:[:patch, :post]

  

end

app/controllers/after_signup_controller.rb
class AfterSignupController < ApplicationController
  before_action :authenticate_user!
  before_action :user_completed?

  def new

  end

  def step_2
    @user = current_user
  end

  def step_2_update
    @user = current_user
    if @user.update_attributes(user_params)
      #render "step_#{@user.usr_type}"
      redirect_to action: "step_#{@user.usr_type}"
    else
      render step_2
    end
  end

  def step_guest
    @user = current_user
  end

  def step_guest_update
    @user = current_user
    if @user.update_attributes(user_params)
      redirect_to action: 'final_step'
    else
      render step_guest
    end
  end

  def step_showman
    @showman_type = current_user.create_showman_type(attributes = {})
  end

  def step_showman_update
    @showman_type = current_user.showman_type
    if @showman_type.update_attributes(showman_params)
      redirect_to action: 'final_step'
    else
      render step_showman
    end
  end

  def step_restaurant
    @restaurant = current_user.create_restaurant(attributes = {})
  end

  def step_restaurant_update
    @restaurant = current_user.restaurant
    if @restaurant.update_attributes(restaurant_params)
      redirect_to action: 'step_restaurant_types'
    else
      render step_restaurant
    end
  end

  def step_restaurant_types
    @restaurant = current_user.restaurant
    @restaurant_type = @restaurant.create_restaurant_type(attributes = {})
  end

  def step_restaurant_types_update
    @restaurant_type = current_user.restaurant.restaurant_type
    if @restaurant_type.update_attributes(restaurant_type_params)
      redirect_to action: 'step_cuisines'
    else
      render step_restaurant_types
    end
  end

  def step_cuisines
    @restaurant = current_user.restaurant
    @cuisine = @restaurant.create_cuisine(attributes = {})
    # @cuisine = current_user.restaurant.cuisine
  end

  def step_cuisines_update
    @cuisine = current_user.restaurant.cuisine
    if @cuisine.update_attributes(cuisine_params)
      redirect_to action: 'final_step'
    else
      render step_cuisines
    end

  end


  def final_step
    @user = current_user
  end


  def final_step_update
    @user = current_user
    if @user.update_attributes(final_params)
      @user.completed = true
      @user.save
      redirect_to @user
    else
      render final_step
    end

  end

  private
  def user_params
    params.require(:user).permit(:usr_type)
  end

  def showman_params
    params.require(:showman_type).permit(:emcee, :dj, :bartender, :illusionist, :tamada)
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :metro, :tel, :workhours, :delivery,
                                       :parking, :wifi, :average_paybill, :max_guests,
                                       :halls_number, :about)
  end

  def restaurant_type_params
    params.require(:restaurant_type).permit(:bar,
                                            :pub,
                                            :pizza,
                                            :barbeque,
                                            :cafe,
                                            :steakhouse,
                                            :sushi_bar,
                                            :vegan_menu,
                                            :food_court,
                                            :art_cafe)
  end

  def cuisine_params
    params.require(:cuisine).permit(:european,
                                    :chinese,
                                    :author,
                                    :azerbaijanian,
                                    :armenian,
                                    :vietnam,
                                    :thai,
                                    :indian,
                                    :indonesian,
                                    :japan,
                                    :international,
                                    :mexican,
                                    :uzbekian,
                                    :germanian,
                                    :american,
                                    :french,
                                    :italian,
                                    :mediterranian,
                                    :ukrainian,
                                    :czech,
                                    :turkish,
                                    :georgian,
                                    :arab,
                                    :korean,
                                    :panazian)
  end

  def final_params
    params.require(:user).permit(:city, :firstname, :lastname, :country,
                                 :skype, :vkontakte, :odkl, :twitter, :phone, :about)
  end


  def user_completed?
    if current_user.completed
      redirect_to root_path
    end
  end

end

app/helpers/after_signup_helper.rb
module AfterSignupHelper
end

app/views/after_signup/final_step.html.erb
<div class="row">
  <div class="span4 offset1">
    <h1>Почти готово!</h1>

    <h2>Еще немного информации:</h2>

    <%= form_for(@user, url: after_signup_final_step_update_path) do |f| %>
        <% if (@user.usr_type == 'guest') || (@user.usr_type == 'showman') %>
            <%= render partial: 'users/partials/user_info_form_fields', locals: {f: f} %>
            <%= render partial: 'users/partials/contacts_form_fields', locals: {f: f} %>
        <% elsif @user.usr_type == 'restaurant' %>
            <%= render partial: 'users/partials/contacts_form_fields', locals: {f: f} %>
        <% end %>

        <%= f.submit 'Готово', class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/after_signup/step_2.html.erb
<div class="row">
  <div class="small-6 small-offset-4 columns">
    <h2>Тип аккаунта: </h2>
    <br>
    <%= form_for(@user, url: after_signup_step_2_update_path) do |f| %>

        <%= f.label 'Гость' %>
        <%= f.radio_button 'usr_type', 'guest' %>

        <%= f.label 'Артист' %>
        <%= f.radio_button 'usr_type', 'showman' %>

        <%= f.label 'Ресторан' %>
        <%= f.radio_button 'usr_type', 'restaurant' %>

        <%= f.submit 'Далее' %>

    <% end %>

  </div>
</div>

app/views/after_signup/step_cuisines.html.erb
<h2>Выберите кухню вашего ресторана</h2>
<div class="row span10">
  <div class="checkbox">
    <%= form_for(@cuisine, url: after_signup_step_cuisines_update_path) do |f| %>
        <%= render partial: 'cuisines/partials/cuisines_form_fields', locals: {f: f} %>
        <%= f.submit 'Далее >', class: "btn btn-large btn-primary" %>

    <% end %>

  </div>
</div>

app/views/after_signup/step_guest.html.erb
<!-- TODO: придумать что тут будет для обычных пользователей -->
<div class="row">
  <div class="span6 offset3">

    <%= form_for(@user, url: after_signup_step_guest_update_path) do |f| %>
        <%= f.label 'Firstname' %>
        <%= f.text_field :firstname %>

        <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/after_signup/step_restaurant.html.erb
<div class="row">
  <div class="span6 offset3">

    <%= form_for(@restaurant, url: after_signup_step_restaurant_update_path) do |f| %>
        <%= render partial: 'restaurants/partials/restaurant_form_fields',
                   locals: {f: f} %>
        <%= f.submit 'Далее >', class: 'btn btn-lg btn-primary' %>

    <% end %>
  </div>
</div>

app/views/after_signup/step_restaurant_types.html.erb
<div class="row">
  <div class="span6 offset3">

    <%= form_for(@restaurant_type, url: after_signup_step_restaurant_types_update_path) do |f| %>
        <%= render partial: 'restaurant_types/partials/restaurant_types_form_fields', locals: {f: f} %>
        <%= f.submit 'Далее >', class: 'btn btn-lg btn-primary' %>
    <% end %>

  </div>
</div>

app/views/after_signup/step_showman.html.erb
<div class="row">
  <div class="medium-6 medium-offset-3">

    <%= form_for(@showman_type, url: after_signup_step_showman_update_path) do |f| %>
        <%= render partial: 'showman_types/partials/showman_types_form_fields', locals: {f: f} %>
        <%= f.submit 'Сохранить', class: 'btn btn-lg btn-primary' %>
    <% end %>
  </div>
</div>